services:
  amnezia:
    build:
      context: ./amnezia
    image: amnezia-client:slkjdfsafkjsa
    container_name: amnezia
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 1.0.0.1
    devices:
      - /dev/net/tun
    volumes:
      # Forward X11 socket so GUI shows up on host
      - /tmp/.X11-unix:/tmp/.X11-unix

      # Mount your real Amnezia configs into container's home
      - ${HOME}/.config/AmneziaVPN.ORG:/root/.config/AmneziaVPN.ORG:ro

    environment:
      - DISPLAY=${DISPLAY}
    #restart: unless-stopped

  chrome:
    build:
      context: ./chromium   # directory with Dockerfile below
      args:
        UID: ${UID}
        GID: ${GID}
    image: chromium:ewkfjlkdsafjlkj
    container_name: chrome
    network_mode: "service:amnezia"  # 🔑 force Chrome into VPN namespace
    shm_size: 2g
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # 🔊 Pulse (pipewire-pulse) socket & runtime dir
      - /run/user/${UID}/pulse:/run/user/${UID}/pulse
      # 🔐 Pulse cookie for auth (host → container). Adjust host path if your user isn’t vi
      - ${HOME}/.config/pulse/cookie:/home/chromium/.config/pulse/cookie:ro
      - ./chromium/data:/home/chromium/.config/chromium  # Volume for storing Chromium user data
    devices:
      - /dev/snd
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/dri:/dev/dri          # 🎨 GPU acceleration
    user: "${UID}:${GID}"
    # Matching your user’s groups helps with devices like /dev/snd (optional if using Pulse socket)
    group_add:
      - audio
      - video
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/${UID}/pulse/native
    #restart: unless-stopped
